apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rosa-cluster-create-pipeline
spec:
  tasks:
    - name: rosa-cluster-create
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/xinredhat/rhtap-e2e.git
          - name: revision
            value: rosa_testing
          - name: pathInRepo
            value: integration/deploy-cluster-task.yaml